import { PresetLocation } from "./types";

export const INDIA_LOCATIONS: PresetLocation[] = [
  {
    id: "delhi",
    name: "Imperial Delhi",
    coordinatesStr: "N 28°36' / E 77°12'",
    x: 37,
    y: 28,
    lat: 28.6139,
    lng: 77.2090,
    category: "city",
    subCategoryText: "Imperial Citadel & Capital Seat",
    details: "The legendary seat of dynasties—from the Tomar Rajputs and Delhi Sultanates to the grand Mughals. It rests at the pivotal junction of the Indo-Gangetic Plain and the Aravalli Ridge, commanding trade routes between Central Asia and Bengal."
  },
  {
    id: "agra",
    name: "Citadel of Agra",
    coordinatesStr: "N 27°10' / E 78°01'",
    x: 40,
    y: 33,
    lat: 27.1767,
    lng: 78.0081,
    category: "fort",
    subCategoryText: "Mughal Stronghold",
    details: "Home to the colossal Agra Fort and the Taj Mahal. Rests on the banks of the winding Yamuna River. Agra served as a magnificent capital where emperors designed monumental red-sandstone walls and marble gardens."
  },
  {
    id: "bombay",
    name: "Bombay Harbour",
    coordinatesStr: "N 18°57' / E 72°49'",
    x: 23,
    y: 62,
    lat: 18.952,
    lng: 72.825,
    category: "city",
    subCategoryText: "Maritime Enclave & Port",
    details: "Originally a group of seven swampy islands ceded by Portugal to the British Crown. It evolved into India's premier gateway to the West, leveraging a magnificent deep-water natural harbor shielded from the Arabian monsoon."
  },
  {
    id: "calcutta",
    name: "Fort William, Calcutta",
    coordinatesStr: "N 22°34' / E 88°21'",
    x: 77,
    y: 47,
    lat: 22.5726,
    lng: 88.3639,
    category: "city",
    subCategoryText: "Presidential Headquarters",
    details: "Founded on the marshy banks of the Hooghly River. It rose from three humble jute-weaving villages to become the glittering, neoclassical capital of the British Raj, driven by tea, silk, and indigo riches."
  },
  {
    id: "goa",
    name: "Golden Velha Goa",
    coordinatesStr: "N 15°29' / E 73°49'",
    x: 25,
    y: 71,
    lat: 15.4909,
    lng: 73.8278,
    category: "city",
    subCategoryText: "Portuguese Viceroyalty",
    details: "The crown jewel of the Portuguese Estado da Índia, captured by Afonso de Albuquerque in 1510. It served as the crucial node of the Arabian horse trade, pepper routing, and Jesuit scholastic missions."
  },
  {
    id: "hampi",
    name: "Ruins of Hampi (Vijayanagara)",
    coordinatesStr: "N 15°20' / E 76°27'",
    x: 35,
    y: 72,
    lat: 15.3350,
    lng: 76.4600,
    category: "city",
    subCategoryText: "Medieval Capital Ruins",
    details: "The monumental capital of the Vijayanagara Empire, surrounded by a bizarre landscape of giant granite boulders beside the Tungabhadra River. It fell after the fateful Battle of Talikota in 1565."
  },
  {
    id: "mysore",
    name: "Kingdom of Mysore",
    coordinatesStr: "N 12°17' / E 76°38'",
    x: 35,
    y: 81,
    lat: 12.2958,
    lng: 76.6394,
    category: "city",
    subCategoryText: "Principal State Seat",
    details: "Ruled by the Wodeyar line and briefly the military geniuses Hyder Ali and Tipu Sultan—the Tiger of Mysore. Celebrated for sandalwood forests, military rocket technology, and sprawling palace architectures."
  },
  {
    id: "jaipur",
    name: "The Pink City of Jaipur",
    coordinatesStr: "N 26°55' / E 75°47'",
    x: 31,
    y: 31,
    lat: 26.9124,
    lng: 75.7873,
    category: "city",
    subCategoryText: "Rajput Citadel",
    details: "Designed in 1727 by Maharaja Sawai Jai Singh II using advanced Vastu Shastra geometry. Located in the desert-fringe lands of Rajputana, it utilizes high stucco walls painted in welcoming terracotta-rose hues."
  },
  {
    id: "ganges",
    name: "The Sacred Ganges",
    coordinatesStr: "N 25°18' / E 83°00'",
    x: 58,
    y: 36,
    lat: 25.3176,
    lng: 83.0062,
    category: "river",
    subCategoryText: "Imperial Lifeline Watershed",
    details: "Sourced from the Gangotri glacier in high Himalaya, this grand river forms the fertile agricultural core of India. It has nurtured civilizations, sacred ghats like Varanasi, and grand empires for three millennia."
  },
  {
    id: "indus",
    name: "The Mighty Indus Basin",
    coordinatesStr: "N 31°10' / E 72°30'",
    x: 20,
    y: 19,
    lat: 31.1660,
    lng: 72.5000,
    category: "river",
    subCategoryText: "Cradle of Empires",
    details: "Drawing its waters from Tibet, the Indus flows past Gilgit and Punjab, feeding five rivers into Sindh's dry planes. It is the linguistic origin of the name 'India' and host to the oldest civilizations."
  },
  {
    id: "brahmaputra",
    name: "The River Brahmaputra",
    coordinatesStr: "N 26°10' / E 92°00'",
    x: 88,
    y: 36,
    lat: 26.1400,
    lng: 91.7300,
    category: "river",
    subCategoryText: "Sovereign Eastern River",
    details: "Known as the Yarlung Tsangpo in Tibet, it bursts through deep Himalayan gorges into the plains of Assam. Red with iron-rich silt, it creates massive fertile deltas on its journey to join the Ganges."
  },
  {
    id: "godavari",
    name: "Southern Godavari",
    coordinatesStr: "N 16°59' / E 81°47'",
    x: 48,
    y: 69,
    lat: 16.9800,
    lng: 81.7800,
    category: "river",
    subCategoryText: "The Southern Gange",
    details: "The longest river in South India, flowing eastward across the Deccan Plateau from its Western Ghats origin in Trimbakeshwar. It creates a vast, highly fertile agricultural delta on the Coromandel coast."
  },
  {
    id: "himalayas",
    name: "The Northern Himalayas",
    coordinatesStr: "N 32°30' / E 79°00'",
    x: 48,
    y: 12,
    lat: 32.5000,
    lng: 79.0000,
    category: "mountain",
    subCategoryText: "The Snowy Crown Bastion",
    details: "The youngest and tallest mountains on Earth, acting as an impassable climatic and military wall guarding the Indian peninsula from freeze-winds and Central Asian hordes alike."
  },
  {
    id: "western_ghats",
    name: "Western Ghats Range",
    coordinatesStr: "N 14°00' / E 74°10'",
    x: 26,
    y: 78,
    lat: 14.0000,
    lng: 74.1600,
    category: "mountain",
    subCategoryText: "The Sahyadri Cloud Forests",
    details: "An ancient mountain wall running parallel to India's west coast. It blocks moisture-laden monsoons, feeding peninsular rivers and providing high basalt peaks ideal for Maratha mountain garrisons."
  },
  {
    id: "deccan_plateau",
    name: "The Deccan Plateau",
    coordinatesStr: "N 19°00' / E 77°00'",
    x: 42,
    y: 61,
    lat: 19.0000,
    lng: 77.0000,
    category: "plateau",
    subCategoryText: "Basalt Peninsula Uplands",
    details: "A massive triangular tableland bounded by the Western and Eastern Ghats. Rich in black volcanic soil ideal for cotton, its fortified hills became iconic strongholds for the Deccan Sultanates."
  },
  {
    id: "gangetic_plains",
    name: "The Indo-Gangetic Plain",
    coordinatesStr: "N 26°30' / E 81°00'",
    x: 52,
    y: 31,
    lat: 26.5000,
    lng: 81.0000,
    category: "plain",
    subCategoryText: "Ancient Heartland Basin",
    details: "A colossal, flat alluvial plain fed by the Ganges-Yamuna system. It contains the highest population density, supporting agrarian empires from Maurya and Gupta dynasties down to the modern epoch."
  }
];

export const WORLD_LOCATIONS: PresetLocation[] = [
  {
    id: "london",
    name: "London (Thamesis Bank)",
    coordinatesStr: "N 51°30' / W 0°07'",
    x: 42,
    y: 28,
    lat: 51.5074,
    lng: -0.1278,
    category: "city",
    subCategoryText: "Imperial Industrial Sovereign",
    details: "Sited along the tidal River Thames. From Roman 'Londinium' to the pivot of the 18th-century industrial and naval empire, holding the Royal Society archives and global trading cables."
  },
  {
    id: "rome",
    name: "Rome, Eternal Seat",
    coordinatesStr: "N 41°54' / E 12°29'",
    x: 46,
    y: 34,
    lat: 41.9028,
    lng: 12.4964,
    category: "city",
    subCategoryText: "Forum of Hand-Carved Marble",
    details: "Nurtured on the seven hills beside the Tiber River. It grew into the ultimate model of European military and civil administration. Landmark ruins of law-givers, Aqueducts, and Senate stone."
  },
  {
    id: "cairo",
    name: "Cairo & The Pyramids",
    coordinatesStr: "N 30°02' / E 31°14'",
    x: 52,
    y: 40,
    lat: 30.0444,
    lng: 31.2357,
    category: "city",
    subCategoryText: "Gateway of Dynastic Sands",
    details: "Commanding the apex of the fertile Nile Delta. Cairo has witnessed millenniums of crowns, from ancient Pharaohs at nearby Memphis to Islamic scholars at the magnificent Al-Azhar Mosque."
  },
  {
    id: "kyoto",
    name: "Imperial Kyoto",
    coordinatesStr: "N 35°01' / E 135°45'",
    x: 82,
    y: 38,
    lat: 35.0116,
    lng: 135.7681,
    category: "city",
    subCategoryText: "Seat of the Chrysanthemum Throne",
    details: "The thousands-years capital of Japan, nestled inside mountains. It served as the ultimate canvas of scholarly aesthetics, zen gardens, hand-painted screens, and Imperial court ritualism."
  },
  {
    id: "istanbul",
    name: "Constantinople / Istanbul",
    coordinatesStr: "N 41°00' / E 28°57'",
    x: 51,
    y: 33,
    lat: 41.0082,
    lng: 28.9784,
    category: "city",
    subCategoryText: "Bridge of Two Continents",
    details: "Overlooking the golden horn of the Bosporus. It transitioned from Byzantine Christianity's heart to the Ottoman Empire's magnificent sovereign throne, controlling the Spice Road flows."
  },
  {
    id: "beijing",
    name: "Forbidden City, Peking",
    coordinatesStr: "N 39°54' / E 116°23'",
    x: 77,
    y: 35,
    lat: 39.9042,
    lng: 116.4074,
    category: "city",
    subCategoryText: "Qing Dynasty Palace Grounds",
    details: "The monumental heart of the Middle Kingdom, built with symmetrical celestial grids. Surrounded by grand moats, high crimson walls, and gold-glazed tiles harboring the Son of Heaven."
  },
  {
    id: "cuzco",
    name: "Cuzco Citadel",
    coordinatesStr: "S 13°31' / W 71°58'",
    x: 27,
    y: 69,
    lat: -13.5319,
    lng: -71.9675,
    category: "city",
    subCategoryText: "Inca Administrative Center",
    details: "Laid out in the shape of a sacred puma at 11,000 feet. Cuzco is an architectural marvel of interlocking, dry-stone ashlar masonry capable of withstanding the fiercest Andes tremors."
  },
  {
    id: "paris",
    name: "Metropolis of Paris",
    coordinatesStr: "N 48°51' / E 2°21'",
    x: 44,
    y: 30,
    lat: 48.8566,
    lng: 2.3522,
    category: "city",
    subCategoryText: "Capital of Philosophy & Art",
    details: "Resting on the curves of the Seine River. The epicenter of the Age of Enlightenment, Gothic spires, and Napoleonic grand plans, reshaping global politics and standard map science."
  },
  {
    id: "nile",
    name: "The River Nile",
    coordinatesStr: "N 19°30' / E 33°10'",
    x: 53,
    y: 47,
    lat: 19.5000,
    lng: 33.1600,
    category: "river",
    subCategoryText: "Father of River Valleys",
    details: "The longest river in the world, originating in East Africa's lakes and flowing north into the Mediterranean. Its black alluvial mud deposits sustained dynasties, calendar calculations, and papyrus harvesting."
  },
  {
    id: "amazon",
    name: "The Deep Amazon Basin",
    coordinatesStr: "S 3°10' / W 60°02'",
    x: 29,
    y: 62,
    lat: -3.1600,
    lng: -60.0300,
    category: "river",
    subCategoryText: "Watershed of the Equator",
    details: "A gargantuan river flowing through dense, untamed rainforests. It carries more water volume than the top seven rivers combined, fueling legends of hidden gold citadels like El Dorado."
  },
  {
    id: "yangtze",
    name: "The Golden Yangtze",
    coordinatesStr: "N 31°12' / E 112°00'",
    x: 75,
    y: 39,
    lat: 31.2000,
    lng: 112.0000,
    category: "river",
    subCategoryText: "Empire-Unifying Waterway",
    details: "Spanning from Tibet to the East China Sea. It is the historic cultural divide between Northern wheat regions and Southern rice empires, hosting massive transport fleets and old poets."
  },
  {
    id: "the_alps",
    name: "The Majestic Alps",
    coordinatesStr: "N 46°30' / E 10°00'",
    x: 45,
    y: 32,
    lat: 46.5000,
    lng: 10.0000,
    category: "mountain",
    subCategoryText: "Snow Peak European Wall",
    details: "A crescent peak chain defining Europe's climate, culture, and high passes. Hannibal crossed its freezing heights with war elephants, and castle fiefdoms guarded its deep merchant tunnels."
  },
  {
    id: "the_andes",
    name: "The Andes Range",
    coordinatesStr: "S 15°00' / W 70°00'",
    x: 27,
    y: 71,
    lat: -15.0000,
    lng: -70.0000,
    category: "mountain",
    subCategoryText: "Spine of South America",
    details: "The longest continental mountain range, forming an immense high altitudes wall along the Pacific coast, keeping clouds, hosting terrace farming, and creating unique micro-climates."
  },
  {
    id: "sahara",
    name: "Great Sahara Desert",
    coordinatesStr: "N 23°00' / E 11°00'",
    x: 44,
    y: 45,
    lat: 23.0000,
    lng: 11.0000,
    category: "plain",
    subCategoryText: "The Amber Sea of Dunes",
    details: "A massive expanse of sand, rock, and ancient salt basins larger than the United States. Navigated by Tuareg salt-caravans using celestial navigation and camels—the ships of the desert."
  },
  {
    id: "tibetan_plateau",
    name: "Tibetan Plateau",
    coordinatesStr: "N 32°00' / E 87°00'",
    x: 70,
    y: 38,
    lat: 32.0000,
    lng: 87.0000,
    category: "plateau",
    subCategoryText: "The Roof of the World",
    details: "An immense, frozen high plateau bordered by the giant peaks of the Himalayas. It serves as the primary water-tower for over three billion humans, fueling Asia's largest river routes."
  },
  {
    id: "eurasian_steppes",
    name: "Vast Eurasian Steppes",
    coordinatesStr: "N 48°00' / E 65°00'",
    x: 59,
    y: 28,
    lat: 48.0000,
    lng: 65.0000,
    category: "plain",
    subCategoryText: "Nomad Grassland Corridors",
    details: "A flat belt of grasslands spanning from Hungary to Manchuria. It served as a nomadic superhighway for Scythians, Huns, and the golden hordes of Genghis Khan riding high-velocity ponies."
  }
];
